# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: admSupervisionVentes
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: M2FkNjMwN2NhNjc5ZGEzMjcxYmZlNThhNTIzMTUwYzBkNTBkMGM0YmQ1YmY0NDU2MTBhOGMyNTdiZGZjMTE5ZWRlNmNiMzM3NWM5ZTQ4YTYyNWQ5YzFlMDRjZDBkZGQ3ZGQ3YzRhMTM1ZjE0NjhkYmUyZDY4MGU5OWQ2ZDZlYjI=
