export enum TypeActionAudit {
  CONNEXION = 'CONNEXION',

  DECONNEXION = 'DECONNEXION',

  CREATION = 'CREATION',

  MODIFICATION = 'MODIFICATION',

  DESACTIVATION = 'DESACTIVATION',

  CHANGEMENT_PRIX = 'CHANGEMENT_PRIX',

  CHANGEMENT_TAUX_REDEVANCE = 'CHANGEMENT_TAUX_REDEVANCE',

  CHANGEMENT_CODE_BARRES = 'CHANGEMENT_CODE_BARRES',

  VENTE_VALIDEE = 'VENTE_VALIDEE',

  VENTE_ANNULEE = 'VENTE_ANNULEE',

  RETOUR_VENTE = 'RETOUR_VENTE',

  MOUVEMENT_STOCK = 'MOUVEMENT_STOCK',

  INVENTAIRE = 'INVENTAIRE',

  PARAMETRAGE = 'PARAMETRAGE',

  EXPORT = 'EXPORT',
}
