import { Routes } from '@angular/router';

import { BusinessRouteAccessService } from 'app/core/auth/business-route-access.service';

const routes: Routes = [
  {
    path: 'authority',
    data: { pageTitle: 'admSupervisionVentesApp.adminAuthority.home.title', feature: 'settings' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./admin/authority/authority.routes'),
  },
  {
    path: 'boutique',
    data: { pageTitle: 'admSupervisionVentesApp.boutique.home.title', feature: 'boutiques' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./boutique/boutique.routes'),
  },
  {
    path: 'locataire',
    data: { pageTitle: 'admSupervisionVentesApp.locataire.home.title', feature: 'locataires' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./locataire/locataire.routes'),
  },
  {
    path: 'exploitation-boutique',
    data: { pageTitle: 'admSupervisionVentesApp.exploitationBoutique.home.title', feature: 'exploitations' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./exploitation-boutique/exploitation-boutique.routes'),
  },
  {
    path: 'profil-metier',
    data: { pageTitle: 'admSupervisionVentesApp.profilMetier.home.title', feature: 'settings' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./profil-metier/profil-metier.routes'),
  },
  {
    path: 'permission-metier',
    data: { pageTitle: 'admSupervisionVentesApp.permissionMetier.home.title', feature: 'settings' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./permission-metier/permission-metier.routes'),
  },
  {
    path: 'affectation-utilisateur',
    data: { pageTitle: 'admSupervisionVentesApp.affectationUtilisateur.home.title', feature: 'users' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./affectation-utilisateur/affectation-utilisateur.routes'),
  },
  {
    path: 'groupe-article',
    data: { pageTitle: 'admSupervisionVentesApp.groupeArticle.home.title', feature: 'produits' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./groupe-article/groupe-article.routes'),
  },
  {
    path: 'famille-article',
    data: { pageTitle: 'admSupervisionVentesApp.familleArticle.home.title', feature: 'produits' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./famille-article/famille-article.routes'),
  },
  {
    path: 'sous-famille-article',
    data: { pageTitle: 'admSupervisionVentesApp.sousFamilleArticle.home.title', feature: 'produits' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./sous-famille-article/sous-famille-article.routes'),
  },
  {
    path: 'unite-mesure',
    data: { pageTitle: 'admSupervisionVentesApp.uniteMesure.home.title', feature: 'produits' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./unite-mesure/unite-mesure.routes'),
  },
  {
    path: 'produit',
    data: { pageTitle: 'admSupervisionVentesApp.produit.home.title', feature: 'produits' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./produit/produit.routes'),
  },
  {
    path: 'tarif-produit',
    data: { pageTitle: 'admSupervisionVentesApp.tarifProduit.home.title', feature: 'produits' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./tarif-produit/tarif-produit.routes'),
  },
  {
    path: 'code-barres-produit',
    data: { pageTitle: 'admSupervisionVentesApp.codeBarresProduit.home.title', feature: 'produits' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./code-barres-produit/code-barres-produit.routes'),
  },
  {
    path: 'historique-code-barres',
    data: { pageTitle: 'admSupervisionVentesApp.historiqueCodeBarres.home.title', feature: 'produits' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./historique-code-barres/historique-code-barres.routes'),
  },
  {
    path: 'parametre-code-barres',
    data: { pageTitle: 'admSupervisionVentesApp.parametreCodeBarres.home.title', features: ['settings', 'produits'] },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./parametre-code-barres/parametre-code-barres.routes'),
  },
  {
    path: 'lot-etiquettes',
    data: { pageTitle: 'admSupervisionVentesApp.lotEtiquettes.home.title', feature: 'produits' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./lot-etiquettes/lot-etiquettes.routes'),
  },
  {
    path: 'etiquette-produit',
    data: { pageTitle: 'admSupervisionVentesApp.etiquetteProduit.home.title', feature: 'produits' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./etiquette-produit/etiquette-produit.routes'),
  },
  {
    path: 'scan-inconnu',
    data: { pageTitle: 'admSupervisionVentesApp.scanInconnu.home.title', features: ['produits', 'caisse'] },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./scan-inconnu/scan-inconnu.routes'),
  },
  {
    path: 'mode-paiement-ref',
    data: { pageTitle: 'admSupervisionVentesApp.modePaiementRef.home.title', features: ['settings', 'caisse', 'redevances'] },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./mode-paiement-ref/mode-paiement-ref.routes'),
  },
  {
    path: 'vente',
    data: { pageTitle: 'admSupervisionVentesApp.vente.home.title', feature: 'caisse' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./vente/vente.routes'),
  },
  {
    path: 'ligne-vente',
    data: { pageTitle: 'admSupervisionVentesApp.ligneVente.home.title', feature: 'caisse' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./ligne-vente/ligne-vente.routes'),
  },
  {
    path: 'paiement-vente',
    data: { pageTitle: 'admSupervisionVentesApp.paiementVente.home.title', feature: 'caisse' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./paiement-vente/paiement-vente.routes'),
  },
  {
    path: 'operation-corrective-vente',
    data: { pageTitle: 'admSupervisionVentesApp.operationCorrectiveVente.home.title', feature: 'caisse' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./operation-corrective-vente/operation-corrective-vente.routes'),
  },
  {
    path: 'ticket-caisse',
    data: { pageTitle: 'admSupervisionVentesApp.ticketCaisse.home.title', feature: 'caisse' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./ticket-caisse/ticket-caisse.routes'),
  },
  {
    path: 'depot-stock',
    data: { pageTitle: 'admSupervisionVentesApp.depotStock.home.title', feature: 'stock' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./depot-stock/depot-stock.routes'),
  },
  {
    path: 'stock-produit',
    data: { pageTitle: 'admSupervisionVentesApp.stockProduit.home.title', feature: 'stock' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./stock-produit/stock-produit.routes'),
  },
  {
    path: 'mouvement-stock',
    data: { pageTitle: 'admSupervisionVentesApp.mouvementStock.home.title', feature: 'stock' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./mouvement-stock/mouvement-stock.routes'),
  },
  {
    path: 'ligne-mouvement-stock',
    data: { pageTitle: 'admSupervisionVentesApp.ligneMouvementStock.home.title', feature: 'stock' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./ligne-mouvement-stock/ligne-mouvement-stock.routes'),
  },
  {
    path: 'reception-produit',
    data: { pageTitle: 'admSupervisionVentesApp.receptionProduit.home.title', feature: 'stock' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./reception-produit/reception-produit.routes'),
  },
  {
    path: 'ligne-reception-produit',
    data: { pageTitle: 'admSupervisionVentesApp.ligneReceptionProduit.home.title', feature: 'stock' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./ligne-reception-produit/ligne-reception-produit.routes'),
  },
  {
    path: 'inventaire-stock',
    data: { pageTitle: 'admSupervisionVentesApp.inventaireStock.home.title', feature: 'stock' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./inventaire-stock/inventaire-stock.routes'),
  },
  {
    path: 'ligne-inventaire-stock',
    data: { pageTitle: 'admSupervisionVentesApp.ligneInventaireStock.home.title', feature: 'stock' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./ligne-inventaire-stock/ligne-inventaire-stock.routes'),
  },
  {
    path: 'transfert-stock',
    data: { pageTitle: 'admSupervisionVentesApp.transfertStock.home.title', feature: 'stock' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./transfert-stock/transfert-stock.routes'),
  },
  {
    path: 'ligne-transfert-stock',
    data: { pageTitle: 'admSupervisionVentesApp.ligneTransfertStock.home.title', feature: 'stock' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./ligne-transfert-stock/ligne-transfert-stock.routes'),
  },
  {
    path: 'regle-redevance',
    data: { pageTitle: 'admSupervisionVentesApp.regleRedevance.home.title', feature: 'redevances' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./regle-redevance/regle-redevance.routes'),
  },
  {
    path: 'calcul-redevance',
    data: { pageTitle: 'admSupervisionVentesApp.calculRedevance.home.title', feature: 'redevances' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./calcul-redevance/calcul-redevance.routes'),
  },
  {
    path: 'ligne-calcul-redevance',
    data: { pageTitle: 'admSupervisionVentesApp.ligneCalculRedevance.home.title', feature: 'redevances' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./ligne-calcul-redevance/ligne-calcul-redevance.routes'),
  },
  {
    path: 'paiement-redevance',
    data: { pageTitle: 'admSupervisionVentesApp.paiementRedevance.home.title', feature: 'redevances' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./paiement-redevance/paiement-redevance.routes'),
  },
  {
    path: 'regularisation-redevance',
    data: { pageTitle: 'admSupervisionVentesApp.regularisationRedevance.home.title', feature: 'redevances' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./regularisation-redevance/regularisation-redevance.routes'),
  },
  {
    path: 'journal-audit',
    data: { pageTitle: 'admSupervisionVentesApp.journalAudit.home.title', feature: 'audit' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./journal-audit/journal-audit.routes'),
  },
  {
    path: 'rapport-export',
    data: { pageTitle: 'admSupervisionVentesApp.rapportExport.home.title', feature: 'reporting' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./rapport-export/rapport-export.routes'),
  },
  {
    path: 'parametre-global',
    data: { pageTitle: 'admSupervisionVentesApp.parametreGlobal.home.title', feature: 'settings' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./parametre-global/parametre-global.routes'),
  },
  {
    path: 'user-management',
    data: { pageTitle: 'userManagement.home.title', feature: 'users' },
    canActivate: [BusinessRouteAccessService],
    canActivateChild: [BusinessRouteAccessService],
    loadChildren: () => import('./admin/user-management/user-management.routes'),
  },
  /* jhipster-needle-add-entity-route - JHipster will add entity modules routes here */
];

export default routes;
