package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AffectationUtilisateurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationUtilisateurAllPropertiesEquals(AffectationUtilisateur expected, AffectationUtilisateur actual) {
        assertAffectationUtilisateurAutoGeneratedPropertiesEquals(expected, actual);
        assertAffectationUtilisateurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationUtilisateurAllUpdatablePropertiesEquals(
        AffectationUtilisateur expected,
        AffectationUtilisateur actual
    ) {
        assertAffectationUtilisateurUpdatableFieldsEquals(expected, actual);
        assertAffectationUtilisateurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationUtilisateurAutoGeneratedPropertiesEquals(
        AffectationUtilisateur expected,
        AffectationUtilisateur actual
    ) {
        assertThat(actual)
            .as("Verify AffectationUtilisateur auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationUtilisateurUpdatableFieldsEquals(AffectationUtilisateur expected, AffectationUtilisateur actual) {
        assertThat(actual)
            .as("Verify AffectationUtilisateur relevant properties")
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationUtilisateurUpdatableRelationshipsEquals(
        AffectationUtilisateur expected,
        AffectationUtilisateur actual
    ) {
        assertThat(actual)
            .as("Verify AffectationUtilisateur relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()))
            .satisfies(a -> assertThat(a.getProfil()).as("check profil").isEqualTo(expected.getProfil()));
    }
}
