package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BoutiqueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoutiqueAllPropertiesEquals(Boutique expected, Boutique actual) {
        assertBoutiqueAutoGeneratedPropertiesEquals(expected, actual);
        assertBoutiqueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoutiqueAllUpdatablePropertiesEquals(Boutique expected, Boutique actual) {
        assertBoutiqueUpdatableFieldsEquals(expected, actual);
        assertBoutiqueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoutiqueAutoGeneratedPropertiesEquals(Boutique expected, Boutique actual) {
        assertThat(actual)
            .as("Verify Boutique auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoutiqueUpdatableFieldsEquals(Boutique expected, Boutique actual) {
        assertThat(actual)
            .as("Verify Boutique relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getEmplacement()).as("check emplacement").isEqualTo(expected.getEmplacement()))
            .satisfies(a -> assertThat(a.getTelephone()).as("check telephone").isEqualTo(expected.getTelephone()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoutiqueUpdatableRelationshipsEquals(Boutique expected, Boutique actual) {
        // empty method
    }
}
