package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CalculRedevanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalculRedevanceAllPropertiesEquals(CalculRedevance expected, CalculRedevance actual) {
        assertCalculRedevanceAutoGeneratedPropertiesEquals(expected, actual);
        assertCalculRedevanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalculRedevanceAllUpdatablePropertiesEquals(CalculRedevance expected, CalculRedevance actual) {
        assertCalculRedevanceUpdatableFieldsEquals(expected, actual);
        assertCalculRedevanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalculRedevanceAutoGeneratedPropertiesEquals(CalculRedevance expected, CalculRedevance actual) {
        assertThat(actual)
            .as("Verify CalculRedevance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalculRedevanceUpdatableFieldsEquals(CalculRedevance expected, CalculRedevance actual) {
        assertThat(actual)
            .as("Verify CalculRedevance relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getPeriodeDebut()).as("check periodeDebut").isEqualTo(expected.getPeriodeDebut()))
            .satisfies(a -> assertThat(a.getPeriodeFin()).as("check periodeFin").isEqualTo(expected.getPeriodeFin()))
            .satisfies(a ->
                assertThat(a.getChiffreAffaires())
                    .as("check chiffreAffaires")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getChiffreAffaires())
            )
            .satisfies(a ->
                assertThat(a.getMontantRedevance())
                    .as("check montantRedevance")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantRedevance())
            )
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDateCalcul()).as("check dateCalcul").isEqualTo(expected.getDateCalcul()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalculRedevanceUpdatableRelationshipsEquals(CalculRedevance expected, CalculRedevance actual) {
        assertThat(actual)
            .as("Verify CalculRedevance relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()))
            .satisfies(a -> assertThat(a.getLocataire()).as("check locataire").isEqualTo(expected.getLocataire()));
    }
}
