package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CodeBarresProduitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodeBarresProduitAllPropertiesEquals(CodeBarresProduit expected, CodeBarresProduit actual) {
        assertCodeBarresProduitAutoGeneratedPropertiesEquals(expected, actual);
        assertCodeBarresProduitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodeBarresProduitAllUpdatablePropertiesEquals(CodeBarresProduit expected, CodeBarresProduit actual) {
        assertCodeBarresProduitUpdatableFieldsEquals(expected, actual);
        assertCodeBarresProduitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodeBarresProduitAutoGeneratedPropertiesEquals(CodeBarresProduit expected, CodeBarresProduit actual) {
        assertThat(actual)
            .as("Verify CodeBarresProduit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodeBarresProduitUpdatableFieldsEquals(CodeBarresProduit expected, CodeBarresProduit actual) {
        assertThat(actual)
            .as("Verify CodeBarresProduit relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getPrincipal()).as("check principal").isEqualTo(expected.getPrincipal()))
            .satisfies(a -> assertThat(a.getGenereParSysteme()).as("check genereParSysteme").isEqualTo(expected.getGenereParSysteme()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()))
            .satisfies(a -> assertThat(a.getDateAffectation()).as("check dateAffectation").isEqualTo(expected.getDateAffectation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodeBarresProduitUpdatableRelationshipsEquals(CodeBarresProduit expected, CodeBarresProduit actual) {
        assertThat(actual)
            .as("Verify CodeBarresProduit relationships")
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()));
    }
}
