package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DepotStockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepotStockAllPropertiesEquals(DepotStock expected, DepotStock actual) {
        assertDepotStockAutoGeneratedPropertiesEquals(expected, actual);
        assertDepotStockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepotStockAllUpdatablePropertiesEquals(DepotStock expected, DepotStock actual) {
        assertDepotStockUpdatableFieldsEquals(expected, actual);
        assertDepotStockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepotStockAutoGeneratedPropertiesEquals(DepotStock expected, DepotStock actual) {
        assertThat(actual)
            .as("Verify DepotStock auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepotStockUpdatableFieldsEquals(DepotStock expected, DepotStock actual) {
        assertThat(actual)
            .as("Verify DepotStock relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getEmplacement()).as("check emplacement").isEqualTo(expected.getEmplacement()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepotStockUpdatableRelationshipsEquals(DepotStock expected, DepotStock actual) {
        assertThat(actual)
            .as("Verify DepotStock relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()));
    }
}
