package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EtiquetteProduitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetteProduitAllPropertiesEquals(EtiquetteProduit expected, EtiquetteProduit actual) {
        assertEtiquetteProduitAutoGeneratedPropertiesEquals(expected, actual);
        assertEtiquetteProduitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetteProduitAllUpdatablePropertiesEquals(EtiquetteProduit expected, EtiquetteProduit actual) {
        assertEtiquetteProduitUpdatableFieldsEquals(expected, actual);
        assertEtiquetteProduitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetteProduitAutoGeneratedPropertiesEquals(EtiquetteProduit expected, EtiquetteProduit actual) {
        assertThat(actual)
            .as("Verify EtiquetteProduit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetteProduitUpdatableFieldsEquals(EtiquetteProduit expected, EtiquetteProduit actual) {
        assertThat(actual)
            .as("Verify EtiquetteProduit relevant properties")
            .satisfies(a -> assertThat(a.getQuantite()).as("check quantite").isEqualTo(expected.getQuantite()))
            .satisfies(a -> assertThat(a.getImprimee()).as("check imprimee").isEqualTo(expected.getImprimee()))
            .satisfies(a -> assertThat(a.getDateImpression()).as("check dateImpression").isEqualTo(expected.getDateImpression()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetteProduitUpdatableRelationshipsEquals(EtiquetteProduit expected, EtiquetteProduit actual) {
        assertThat(actual)
            .as("Verify EtiquetteProduit relationships")
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()))
            .satisfies(a -> assertThat(a.getLot()).as("check lot").isEqualTo(expected.getLot()));
    }
}
