package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FamilleArticleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilleArticleAllPropertiesEquals(FamilleArticle expected, FamilleArticle actual) {
        assertFamilleArticleAutoGeneratedPropertiesEquals(expected, actual);
        assertFamilleArticleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilleArticleAllUpdatablePropertiesEquals(FamilleArticle expected, FamilleArticle actual) {
        assertFamilleArticleUpdatableFieldsEquals(expected, actual);
        assertFamilleArticleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilleArticleAutoGeneratedPropertiesEquals(FamilleArticle expected, FamilleArticle actual) {
        assertThat(actual)
            .as("Verify FamilleArticle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilleArticleUpdatableFieldsEquals(FamilleArticle expected, FamilleArticle actual) {
        assertThat(actual)
            .as("Verify FamilleArticle relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilleArticleUpdatableRelationshipsEquals(FamilleArticle expected, FamilleArticle actual) {
        assertThat(actual)
            .as("Verify FamilleArticle relationships")
            .satisfies(a -> assertThat(a.getGroupeArticle()).as("check groupeArticle").isEqualTo(expected.getGroupeArticle()));
    }
}
