package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GroupeArticleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupeArticleAllPropertiesEquals(GroupeArticle expected, GroupeArticle actual) {
        assertGroupeArticleAutoGeneratedPropertiesEquals(expected, actual);
        assertGroupeArticleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupeArticleAllUpdatablePropertiesEquals(GroupeArticle expected, GroupeArticle actual) {
        assertGroupeArticleUpdatableFieldsEquals(expected, actual);
        assertGroupeArticleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupeArticleAutoGeneratedPropertiesEquals(GroupeArticle expected, GroupeArticle actual) {
        assertThat(actual)
            .as("Verify GroupeArticle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupeArticleUpdatableFieldsEquals(GroupeArticle expected, GroupeArticle actual) {
        assertThat(actual)
            .as("Verify GroupeArticle relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupeArticleUpdatableRelationshipsEquals(GroupeArticle expected, GroupeArticle actual) {
        assertThat(actual)
            .as("Verify GroupeArticle relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()));
    }
}
