package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistoriqueCodeBarresAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueCodeBarresAllPropertiesEquals(HistoriqueCodeBarres expected, HistoriqueCodeBarres actual) {
        assertHistoriqueCodeBarresAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoriqueCodeBarresAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueCodeBarresAllUpdatablePropertiesEquals(HistoriqueCodeBarres expected, HistoriqueCodeBarres actual) {
        assertHistoriqueCodeBarresUpdatableFieldsEquals(expected, actual);
        assertHistoriqueCodeBarresUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueCodeBarresAutoGeneratedPropertiesEquals(HistoriqueCodeBarres expected, HistoriqueCodeBarres actual) {
        assertThat(actual)
            .as("Verify HistoriqueCodeBarres auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueCodeBarresUpdatableFieldsEquals(HistoriqueCodeBarres expected, HistoriqueCodeBarres actual) {
        assertThat(actual)
            .as("Verify HistoriqueCodeBarres relevant properties")
            .satisfies(a -> assertThat(a.getAncienCode()).as("check ancienCode").isEqualTo(expected.getAncienCode()))
            .satisfies(a -> assertThat(a.getNouveauCode()).as("check nouveauCode").isEqualTo(expected.getNouveauCode()))
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()))
            .satisfies(a -> assertThat(a.getDateChangement()).as("check dateChangement").isEqualTo(expected.getDateChangement()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueCodeBarresUpdatableRelationshipsEquals(HistoriqueCodeBarres expected, HistoriqueCodeBarres actual) {
        assertThat(actual)
            .as("Verify HistoriqueCodeBarres relationships")
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()));
    }
}
