package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InventaireStockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireStockAllPropertiesEquals(InventaireStock expected, InventaireStock actual) {
        assertInventaireStockAutoGeneratedPropertiesEquals(expected, actual);
        assertInventaireStockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireStockAllUpdatablePropertiesEquals(InventaireStock expected, InventaireStock actual) {
        assertInventaireStockUpdatableFieldsEquals(expected, actual);
        assertInventaireStockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireStockAutoGeneratedPropertiesEquals(InventaireStock expected, InventaireStock actual) {
        assertThat(actual)
            .as("Verify InventaireStock auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireStockUpdatableFieldsEquals(InventaireStock expected, InventaireStock actual) {
        assertThat(actual)
            .as("Verify InventaireStock relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getTypeInventaire()).as("check typeInventaire").isEqualTo(expected.getTypeInventaire()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireStockUpdatableRelationshipsEquals(InventaireStock expected, InventaireStock actual) {
        assertThat(actual)
            .as("Verify InventaireStock relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()))
            .satisfies(a -> assertThat(a.getDepot()).as("check depot").isEqualTo(expected.getDepot()));
    }
}
