package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JournalAuditAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalAuditAllPropertiesEquals(JournalAudit expected, JournalAudit actual) {
        assertJournalAuditAutoGeneratedPropertiesEquals(expected, actual);
        assertJournalAuditAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalAuditAllUpdatablePropertiesEquals(JournalAudit expected, JournalAudit actual) {
        assertJournalAuditUpdatableFieldsEquals(expected, actual);
        assertJournalAuditUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalAuditAutoGeneratedPropertiesEquals(JournalAudit expected, JournalAudit actual) {
        assertThat(actual)
            .as("Verify JournalAudit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalAuditUpdatableFieldsEquals(JournalAudit expected, JournalAudit actual) {
        assertThat(actual)
            .as("Verify JournalAudit relevant properties")
            .satisfies(a -> assertThat(a.getTypeAction()).as("check typeAction").isEqualTo(expected.getTypeAction()))
            .satisfies(a -> assertThat(a.getEntiteConcernee()).as("check entiteConcernee").isEqualTo(expected.getEntiteConcernee()))
            .satisfies(a -> assertThat(a.getIdentifiantEntite()).as("check identifiantEntite").isEqualTo(expected.getIdentifiantEntite()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAdresseIp()).as("check adresseIp").isEqualTo(expected.getAdresseIp()))
            .satisfies(a -> assertThat(a.getDateAction()).as("check dateAction").isEqualTo(expected.getDateAction()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalAuditUpdatableRelationshipsEquals(JournalAudit expected, JournalAudit actual) {
        assertThat(actual)
            .as("Verify JournalAudit relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()));
    }
}
