package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LigneCalculRedevanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneCalculRedevanceAllPropertiesEquals(LigneCalculRedevance expected, LigneCalculRedevance actual) {
        assertLigneCalculRedevanceAutoGeneratedPropertiesEquals(expected, actual);
        assertLigneCalculRedevanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneCalculRedevanceAllUpdatablePropertiesEquals(LigneCalculRedevance expected, LigneCalculRedevance actual) {
        assertLigneCalculRedevanceUpdatableFieldsEquals(expected, actual);
        assertLigneCalculRedevanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneCalculRedevanceAutoGeneratedPropertiesEquals(LigneCalculRedevance expected, LigneCalculRedevance actual) {
        assertThat(actual)
            .as("Verify LigneCalculRedevance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneCalculRedevanceUpdatableFieldsEquals(LigneCalculRedevance expected, LigneCalculRedevance actual) {
        assertThat(actual)
            .as("Verify LigneCalculRedevance relevant properties")
            .satisfies(a ->
                assertThat(a.getBaseCalcul())
                    .as("check baseCalcul")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBaseCalcul())
            )
            .satisfies(a ->
                assertThat(a.getTauxApplique())
                    .as("check tauxApplique")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTauxApplique())
            )
            .satisfies(a ->
                assertThat(a.getMontantRedevance())
                    .as("check montantRedevance")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantRedevance())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneCalculRedevanceUpdatableRelationshipsEquals(LigneCalculRedevance expected, LigneCalculRedevance actual) {
        assertThat(actual)
            .as("Verify LigneCalculRedevance relationships")
            .satisfies(a -> assertThat(a.getCalcul()).as("check calcul").isEqualTo(expected.getCalcul()))
            .satisfies(a -> assertThat(a.getVente()).as("check vente").isEqualTo(expected.getVente()));
    }
}
