package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LigneReceptionProduitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneReceptionProduitAllPropertiesEquals(LigneReceptionProduit expected, LigneReceptionProduit actual) {
        assertLigneReceptionProduitAutoGeneratedPropertiesEquals(expected, actual);
        assertLigneReceptionProduitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneReceptionProduitAllUpdatablePropertiesEquals(
        LigneReceptionProduit expected,
        LigneReceptionProduit actual
    ) {
        assertLigneReceptionProduitUpdatableFieldsEquals(expected, actual);
        assertLigneReceptionProduitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneReceptionProduitAutoGeneratedPropertiesEquals(
        LigneReceptionProduit expected,
        LigneReceptionProduit actual
    ) {
        assertThat(actual)
            .as("Verify LigneReceptionProduit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneReceptionProduitUpdatableFieldsEquals(LigneReceptionProduit expected, LigneReceptionProduit actual) {
        assertThat(actual)
            .as("Verify LigneReceptionProduit relevant properties")
            .satisfies(a ->
                assertThat(a.getQuantiteAttendue())
                    .as("check quantiteAttendue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getQuantiteAttendue())
            )
            .satisfies(a ->
                assertThat(a.getQuantiteRecue())
                    .as("check quantiteRecue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getQuantiteRecue())
            )
            .satisfies(a -> assertThat(a.getEcart()).as("check ecart").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getEcart()))
            .satisfies(a -> assertThat(a.getCodeBarresScanne()).as("check codeBarresScanne").isEqualTo(expected.getCodeBarresScanne()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneReceptionProduitUpdatableRelationshipsEquals(
        LigneReceptionProduit expected,
        LigneReceptionProduit actual
    ) {
        assertThat(actual)
            .as("Verify LigneReceptionProduit relationships")
            .satisfies(a -> assertThat(a.getReception()).as("check reception").isEqualTo(expected.getReception()))
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()));
    }
}
