package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LigneTransfertStockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneTransfertStockAllPropertiesEquals(LigneTransfertStock expected, LigneTransfertStock actual) {
        assertLigneTransfertStockAutoGeneratedPropertiesEquals(expected, actual);
        assertLigneTransfertStockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneTransfertStockAllUpdatablePropertiesEquals(LigneTransfertStock expected, LigneTransfertStock actual) {
        assertLigneTransfertStockUpdatableFieldsEquals(expected, actual);
        assertLigneTransfertStockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneTransfertStockAutoGeneratedPropertiesEquals(LigneTransfertStock expected, LigneTransfertStock actual) {
        assertThat(actual)
            .as("Verify LigneTransfertStock auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneTransfertStockUpdatableFieldsEquals(LigneTransfertStock expected, LigneTransfertStock actual) {
        assertThat(actual)
            .as("Verify LigneTransfertStock relevant properties")
            .satisfies(a ->
                assertThat(a.getQuantite()).as("check quantite").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantite())
            )
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneTransfertStockUpdatableRelationshipsEquals(LigneTransfertStock expected, LigneTransfertStock actual) {
        assertThat(actual)
            .as("Verify LigneTransfertStock relationships")
            .satisfies(a -> assertThat(a.getTransfert()).as("check transfert").isEqualTo(expected.getTransfert()))
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()));
    }
}
