package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LigneVenteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneVenteAllPropertiesEquals(LigneVente expected, LigneVente actual) {
        assertLigneVenteAutoGeneratedPropertiesEquals(expected, actual);
        assertLigneVenteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneVenteAllUpdatablePropertiesEquals(LigneVente expected, LigneVente actual) {
        assertLigneVenteUpdatableFieldsEquals(expected, actual);
        assertLigneVenteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneVenteAutoGeneratedPropertiesEquals(LigneVente expected, LigneVente actual) {
        assertThat(actual)
            .as("Verify LigneVente auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneVenteUpdatableFieldsEquals(LigneVente expected, LigneVente actual) {
        assertThat(actual)
            .as("Verify LigneVente relevant properties")
            .satisfies(a ->
                assertThat(a.getQuantite()).as("check quantite").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantite())
            )
            .satisfies(a ->
                assertThat(a.getPrixUnitaire())
                    .as("check prixUnitaire")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrixUnitaire())
            )
            .satisfies(a ->
                assertThat(a.getRemise()).as("check remise").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRemise())
            )
            .satisfies(a ->
                assertThat(a.getMontantLigne())
                    .as("check montantLigne")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantLigne())
            )
            .satisfies(a -> assertThat(a.getCodeBarresScanne()).as("check codeBarresScanne").isEqualTo(expected.getCodeBarresScanne()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneVenteUpdatableRelationshipsEquals(LigneVente expected, LigneVente actual) {
        assertThat(actual)
            .as("Verify LigneVente relationships")
            .satisfies(a -> assertThat(a.getVente()).as("check vente").isEqualTo(expected.getVente()))
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()));
    }
}
