package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LigneMouvementStockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneMouvementStockAllPropertiesEquals(LigneMouvementStock expected, LigneMouvementStock actual) {
        assertLigneMouvementStockAutoGeneratedPropertiesEquals(expected, actual);
        assertLigneMouvementStockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneMouvementStockAllUpdatablePropertiesEquals(LigneMouvementStock expected, LigneMouvementStock actual) {
        assertLigneMouvementStockUpdatableFieldsEquals(expected, actual);
        assertLigneMouvementStockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneMouvementStockAutoGeneratedPropertiesEquals(LigneMouvementStock expected, LigneMouvementStock actual) {
        assertThat(actual)
            .as("Verify LigneMouvementStock auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneMouvementStockUpdatableFieldsEquals(LigneMouvementStock expected, LigneMouvementStock actual) {
        assertThat(actual)
            .as("Verify LigneMouvementStock relevant properties")
            .satisfies(a ->
                assertThat(a.getQuantite()).as("check quantite").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantite())
            )
            .satisfies(a ->
                assertThat(a.getStockAvant())
                    .as("check stockAvant")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getStockAvant())
            )
            .satisfies(a ->
                assertThat(a.getStockApres())
                    .as("check stockApres")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getStockApres())
            )
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneMouvementStockUpdatableRelationshipsEquals(LigneMouvementStock expected, LigneMouvementStock actual) {
        assertThat(actual)
            .as("Verify LigneMouvementStock relationships")
            .satisfies(a -> assertThat(a.getMouvement()).as("check mouvement").isEqualTo(expected.getMouvement()))
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()))
            .satisfies(a -> assertThat(a.getDepot()).as("check depot").isEqualTo(expected.getDepot()));
    }
}
