package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LigneInventaireStockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneInventaireStockAllPropertiesEquals(LigneInventaireStock expected, LigneInventaireStock actual) {
        assertLigneInventaireStockAutoGeneratedPropertiesEquals(expected, actual);
        assertLigneInventaireStockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneInventaireStockAllUpdatablePropertiesEquals(LigneInventaireStock expected, LigneInventaireStock actual) {
        assertLigneInventaireStockUpdatableFieldsEquals(expected, actual);
        assertLigneInventaireStockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneInventaireStockAutoGeneratedPropertiesEquals(LigneInventaireStock expected, LigneInventaireStock actual) {
        assertThat(actual)
            .as("Verify LigneInventaireStock auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneInventaireStockUpdatableFieldsEquals(LigneInventaireStock expected, LigneInventaireStock actual) {
        assertThat(actual)
            .as("Verify LigneInventaireStock relevant properties")
            .satisfies(a ->
                assertThat(a.getQuantiteTheorique())
                    .as("check quantiteTheorique")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getQuantiteTheorique())
            )
            .satisfies(a ->
                assertThat(a.getQuantiteComptee())
                    .as("check quantiteComptee")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getQuantiteComptee())
            )
            .satisfies(a -> assertThat(a.getEcart()).as("check ecart").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getEcart()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneInventaireStockUpdatableRelationshipsEquals(LigneInventaireStock expected, LigneInventaireStock actual) {
        assertThat(actual)
            .as("Verify LigneInventaireStock relationships")
            .satisfies(a -> assertThat(a.getInventaire()).as("check inventaire").isEqualTo(expected.getInventaire()))
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()));
    }
}
