package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LocataireAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocataireAllPropertiesEquals(Locataire expected, Locataire actual) {
        assertLocataireAutoGeneratedPropertiesEquals(expected, actual);
        assertLocataireAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocataireAllUpdatablePropertiesEquals(Locataire expected, Locataire actual) {
        assertLocataireUpdatableFieldsEquals(expected, actual);
        assertLocataireUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocataireAutoGeneratedPropertiesEquals(Locataire expected, Locataire actual) {
        assertThat(actual)
            .as("Verify Locataire auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocataireUpdatableFieldsEquals(Locataire expected, Locataire actual) {
        assertThat(actual)
            .as("Verify Locataire relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getTypeLocataire()).as("check typeLocataire").isEqualTo(expected.getTypeLocataire()))
            .satisfies(a ->
                assertThat(a.getNumeroIdentification()).as("check numeroIdentification").isEqualTo(expected.getNumeroIdentification())
            )
            .satisfies(a -> assertThat(a.getTelephone()).as("check telephone").isEqualTo(expected.getTelephone()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getAdresse()).as("check adresse").isEqualTo(expected.getAdresse()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocataireUpdatableRelationshipsEquals(Locataire expected, Locataire actual) {
        // empty method
    }
}
