package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LotEtiquettesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotEtiquettesAllPropertiesEquals(LotEtiquettes expected, LotEtiquettes actual) {
        assertLotEtiquettesAutoGeneratedPropertiesEquals(expected, actual);
        assertLotEtiquettesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotEtiquettesAllUpdatablePropertiesEquals(LotEtiquettes expected, LotEtiquettes actual) {
        assertLotEtiquettesUpdatableFieldsEquals(expected, actual);
        assertLotEtiquettesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotEtiquettesAutoGeneratedPropertiesEquals(LotEtiquettes expected, LotEtiquettes actual) {
        assertThat(actual)
            .as("Verify LotEtiquettes auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotEtiquettesUpdatableFieldsEquals(LotEtiquettes expected, LotEtiquettes actual) {
        assertThat(actual)
            .as("Verify LotEtiquettes relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getDateGeneration()).as("check dateGeneration").isEqualTo(expected.getDateGeneration()))
            .satisfies(a -> assertThat(a.getFormatImpression()).as("check formatImpression").isEqualTo(expected.getFormatImpression()))
            .satisfies(a -> assertThat(a.getNombreEtiquettes()).as("check nombreEtiquettes").isEqualTo(expected.getNombreEtiquettes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotEtiquettesUpdatableRelationshipsEquals(LotEtiquettes expected, LotEtiquettes actual) {
        // empty method
    }
}
