package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModePaiementRefAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementRefAllPropertiesEquals(ModePaiementRef expected, ModePaiementRef actual) {
        assertModePaiementRefAutoGeneratedPropertiesEquals(expected, actual);
        assertModePaiementRefAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementRefAllUpdatablePropertiesEquals(ModePaiementRef expected, ModePaiementRef actual) {
        assertModePaiementRefUpdatableFieldsEquals(expected, actual);
        assertModePaiementRefUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementRefAutoGeneratedPropertiesEquals(ModePaiementRef expected, ModePaiementRef actual) {
        assertThat(actual)
            .as("Verify ModePaiementRef auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementRefUpdatableFieldsEquals(ModePaiementRef expected, ModePaiementRef actual) {
        assertThat(actual)
            .as("Verify ModePaiementRef relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementRefUpdatableRelationshipsEquals(ModePaiementRef expected, ModePaiementRef actual) {
        // empty method
    }
}
