package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MouvementStockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMouvementStockAllPropertiesEquals(MouvementStock expected, MouvementStock actual) {
        assertMouvementStockAutoGeneratedPropertiesEquals(expected, actual);
        assertMouvementStockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMouvementStockAllUpdatablePropertiesEquals(MouvementStock expected, MouvementStock actual) {
        assertMouvementStockUpdatableFieldsEquals(expected, actual);
        assertMouvementStockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMouvementStockAutoGeneratedPropertiesEquals(MouvementStock expected, MouvementStock actual) {
        assertThat(actual)
            .as("Verify MouvementStock auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMouvementStockUpdatableFieldsEquals(MouvementStock expected, MouvementStock actual) {
        assertThat(actual)
            .as("Verify MouvementStock relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getTypeMouvement()).as("check typeMouvement").isEqualTo(expected.getTypeMouvement()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDateMouvement()).as("check dateMouvement").isEqualTo(expected.getDateMouvement()))
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMouvementStockUpdatableRelationshipsEquals(MouvementStock expected, MouvementStock actual) {
        assertThat(actual)
            .as("Verify MouvementStock relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()));
    }
}
