package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OperationCorrectiveVenteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperationCorrectiveVenteAllPropertiesEquals(
        OperationCorrectiveVente expected,
        OperationCorrectiveVente actual
    ) {
        assertOperationCorrectiveVenteAutoGeneratedPropertiesEquals(expected, actual);
        assertOperationCorrectiveVenteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperationCorrectiveVenteAllUpdatablePropertiesEquals(
        OperationCorrectiveVente expected,
        OperationCorrectiveVente actual
    ) {
        assertOperationCorrectiveVenteUpdatableFieldsEquals(expected, actual);
        assertOperationCorrectiveVenteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperationCorrectiveVenteAutoGeneratedPropertiesEquals(
        OperationCorrectiveVente expected,
        OperationCorrectiveVente actual
    ) {
        assertThat(actual)
            .as("Verify OperationCorrectiveVente auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperationCorrectiveVenteUpdatableFieldsEquals(
        OperationCorrectiveVente expected,
        OperationCorrectiveVente actual
    ) {
        assertThat(actual)
            .as("Verify OperationCorrectiveVente relevant properties")
            .satisfies(a -> assertThat(a.getTypeOperation()).as("check typeOperation").isEqualTo(expected.getTypeOperation()))
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()))
            .satisfies(a ->
                assertThat(a.getMontantImpact())
                    .as("check montantImpact")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantImpact())
            )
            .satisfies(a -> assertThat(a.getDateOperation()).as("check dateOperation").isEqualTo(expected.getDateOperation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperationCorrectiveVenteUpdatableRelationshipsEquals(
        OperationCorrectiveVente expected,
        OperationCorrectiveVente actual
    ) {
        assertThat(actual)
            .as("Verify OperationCorrectiveVente relationships")
            .satisfies(a -> assertThat(a.getVente()).as("check vente").isEqualTo(expected.getVente()));
    }
}
