package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PaiementRedevanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaiementRedevanceAllPropertiesEquals(PaiementRedevance expected, PaiementRedevance actual) {
        assertPaiementRedevanceAutoGeneratedPropertiesEquals(expected, actual);
        assertPaiementRedevanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaiementRedevanceAllUpdatablePropertiesEquals(PaiementRedevance expected, PaiementRedevance actual) {
        assertPaiementRedevanceUpdatableFieldsEquals(expected, actual);
        assertPaiementRedevanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaiementRedevanceAutoGeneratedPropertiesEquals(PaiementRedevance expected, PaiementRedevance actual) {
        assertThat(actual)
            .as("Verify PaiementRedevance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaiementRedevanceUpdatableFieldsEquals(PaiementRedevance expected, PaiementRedevance actual) {
        assertThat(actual)
            .as("Verify PaiementRedevance relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a ->
                assertThat(a.getMontant()).as("check montant").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMontant())
            )
            .satisfies(a -> assertThat(a.getDatePaiement()).as("check datePaiement").isEqualTo(expected.getDatePaiement()))
            .satisfies(a -> assertThat(a.getModePaiement()).as("check modePaiement").isEqualTo(expected.getModePaiement()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaiementRedevanceUpdatableRelationshipsEquals(PaiementRedevance expected, PaiementRedevance actual) {
        assertThat(actual)
            .as("Verify PaiementRedevance relationships")
            .satisfies(a -> assertThat(a.getCalcul()).as("check calcul").isEqualTo(expected.getCalcul()));
    }
}
