package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PaiementVenteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaiementVenteAllPropertiesEquals(PaiementVente expected, PaiementVente actual) {
        assertPaiementVenteAutoGeneratedPropertiesEquals(expected, actual);
        assertPaiementVenteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaiementVenteAllUpdatablePropertiesEquals(PaiementVente expected, PaiementVente actual) {
        assertPaiementVenteUpdatableFieldsEquals(expected, actual);
        assertPaiementVenteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaiementVenteAutoGeneratedPropertiesEquals(PaiementVente expected, PaiementVente actual) {
        assertThat(actual)
            .as("Verify PaiementVente auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaiementVenteUpdatableFieldsEquals(PaiementVente expected, PaiementVente actual) {
        assertThat(actual)
            .as("Verify PaiementVente relevant properties")
            .satisfies(a ->
                assertThat(a.getMontant()).as("check montant").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMontant())
            )
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getReferencePaiement()).as("check referencePaiement").isEqualTo(expected.getReferencePaiement()))
            .satisfies(a -> assertThat(a.getDatePaiement()).as("check datePaiement").isEqualTo(expected.getDatePaiement()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaiementVenteUpdatableRelationshipsEquals(PaiementVente expected, PaiementVente actual) {
        assertThat(actual)
            .as("Verify PaiementVente relationships")
            .satisfies(a -> assertThat(a.getVente()).as("check vente").isEqualTo(expected.getVente()))
            .satisfies(a -> assertThat(a.getModePaiement()).as("check modePaiement").isEqualTo(expected.getModePaiement()));
    }
}
