package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParametreGlobalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametreGlobalAllPropertiesEquals(ParametreGlobal expected, ParametreGlobal actual) {
        assertParametreGlobalAutoGeneratedPropertiesEquals(expected, actual);
        assertParametreGlobalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametreGlobalAllUpdatablePropertiesEquals(ParametreGlobal expected, ParametreGlobal actual) {
        assertParametreGlobalUpdatableFieldsEquals(expected, actual);
        assertParametreGlobalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametreGlobalAutoGeneratedPropertiesEquals(ParametreGlobal expected, ParametreGlobal actual) {
        assertThat(actual)
            .as("Verify ParametreGlobal auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametreGlobalUpdatableFieldsEquals(ParametreGlobal expected, ParametreGlobal actual) {
        assertThat(actual)
            .as("Verify ParametreGlobal relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getValeur()).as("check valeur").isEqualTo(expected.getValeur()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametreGlobalUpdatableRelationshipsEquals(ParametreGlobal expected, ParametreGlobal actual) {
        // empty method
    }
}
