package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PermissionMetierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionMetierAllPropertiesEquals(PermissionMetier expected, PermissionMetier actual) {
        assertPermissionMetierAutoGeneratedPropertiesEquals(expected, actual);
        assertPermissionMetierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionMetierAllUpdatablePropertiesEquals(PermissionMetier expected, PermissionMetier actual) {
        assertPermissionMetierUpdatableFieldsEquals(expected, actual);
        assertPermissionMetierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionMetierAutoGeneratedPropertiesEquals(PermissionMetier expected, PermissionMetier actual) {
        assertThat(actual)
            .as("Verify PermissionMetier auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionMetierUpdatableFieldsEquals(PermissionMetier expected, PermissionMetier actual) {
        assertThat(actual)
            .as("Verify PermissionMetier relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getModule()).as("check module").isEqualTo(expected.getModule()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionMetierUpdatableRelationshipsEquals(PermissionMetier expected, PermissionMetier actual) {
        assertThat(actual)
            .as("Verify PermissionMetier relationships")
            .satisfies(a -> assertThat(a.getProfilses()).as("check profilses").isEqualTo(expected.getProfilses()));
    }
}
