package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProduitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitAllPropertiesEquals(Produit expected, Produit actual) {
        assertProduitAutoGeneratedPropertiesEquals(expected, actual);
        assertProduitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitAllUpdatablePropertiesEquals(Produit expected, Produit actual) {
        assertProduitUpdatableFieldsEquals(expected, actual);
        assertProduitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitAutoGeneratedPropertiesEquals(Produit expected, Produit actual) {
        assertThat(actual)
            .as("Verify Produit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitUpdatableFieldsEquals(Produit expected, Produit actual) {
        assertThat(actual)
            .as("Verify Produit relevant properties")
            .satisfies(a -> assertThat(a.getCodeInterne()).as("check codeInterne").isEqualTo(expected.getCodeInterne()))
            .satisfies(a -> assertThat(a.getDesignation()).as("check designation").isEqualTo(expected.getDesignation()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getTypePrix()).as("check typePrix").isEqualTo(expected.getTypePrix()))
            .satisfies(a ->
                assertThat(a.getPrixVente()).as("check prixVente").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrixVente())
            )
            .satisfies(a ->
                assertThat(a.getTauxRedevanceApplicable())
                    .as("check tauxRedevanceApplicable")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTauxRedevanceApplicable())
            )
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduitUpdatableRelationshipsEquals(Produit expected, Produit actual) {
        assertThat(actual)
            .as("Verify Produit relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()))
            .satisfies(a -> assertThat(a.getGroupeArticle()).as("check groupeArticle").isEqualTo(expected.getGroupeArticle()))
            .satisfies(a -> assertThat(a.getFamilleArticle()).as("check familleArticle").isEqualTo(expected.getFamilleArticle()))
            .satisfies(a ->
                assertThat(a.getSousFamilleArticle()).as("check sousFamilleArticle").isEqualTo(expected.getSousFamilleArticle())
            )
            .satisfies(a -> assertThat(a.getUniteMesure()).as("check uniteMesure").isEqualTo(expected.getUniteMesure()));
    }
}
