package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfilMetierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilMetierAllPropertiesEquals(ProfilMetier expected, ProfilMetier actual) {
        assertProfilMetierAutoGeneratedPropertiesEquals(expected, actual);
        assertProfilMetierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilMetierAllUpdatablePropertiesEquals(ProfilMetier expected, ProfilMetier actual) {
        assertProfilMetierUpdatableFieldsEquals(expected, actual);
        assertProfilMetierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilMetierAutoGeneratedPropertiesEquals(ProfilMetier expected, ProfilMetier actual) {
        assertThat(actual)
            .as("Verify ProfilMetier auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilMetierUpdatableFieldsEquals(ProfilMetier expected, ProfilMetier actual) {
        assertThat(actual)
            .as("Verify ProfilMetier relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilMetierUpdatableRelationshipsEquals(ProfilMetier expected, ProfilMetier actual) {
        assertThat(actual)
            .as("Verify ProfilMetier relationships")
            .satisfies(a -> assertThat(a.getPermissionses()).as("check permissionses").isEqualTo(expected.getPermissionses()));
    }
}
