package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RapportExportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRapportExportAllPropertiesEquals(RapportExport expected, RapportExport actual) {
        assertRapportExportAutoGeneratedPropertiesEquals(expected, actual);
        assertRapportExportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRapportExportAllUpdatablePropertiesEquals(RapportExport expected, RapportExport actual) {
        assertRapportExportUpdatableFieldsEquals(expected, actual);
        assertRapportExportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRapportExportAutoGeneratedPropertiesEquals(RapportExport expected, RapportExport actual) {
        assertThat(actual)
            .as("Verify RapportExport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRapportExportUpdatableFieldsEquals(RapportExport expected, RapportExport actual) {
        assertThat(actual)
            .as("Verify RapportExport relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getTypeRapport()).as("check typeRapport").isEqualTo(expected.getTypeRapport()))
            .satisfies(a -> assertThat(a.getFormat()).as("check format").isEqualTo(expected.getFormat()))
            .satisfies(a -> assertThat(a.getPeriodeDebut()).as("check periodeDebut").isEqualTo(expected.getPeriodeDebut()))
            .satisfies(a -> assertThat(a.getPeriodeFin()).as("check periodeFin").isEqualTo(expected.getPeriodeFin()))
            .satisfies(a -> assertThat(a.getCheminFichier()).as("check cheminFichier").isEqualTo(expected.getCheminFichier()))
            .satisfies(a -> assertThat(a.getDateGeneration()).as("check dateGeneration").isEqualTo(expected.getDateGeneration()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRapportExportUpdatableRelationshipsEquals(RapportExport expected, RapportExport actual) {
        assertThat(actual)
            .as("Verify RapportExport relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()))
            .satisfies(a -> assertThat(a.getLocataire()).as("check locataire").isEqualTo(expected.getLocataire()));
    }
}
