package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReceptionProduitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceptionProduitAllPropertiesEquals(ReceptionProduit expected, ReceptionProduit actual) {
        assertReceptionProduitAutoGeneratedPropertiesEquals(expected, actual);
        assertReceptionProduitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceptionProduitAllUpdatablePropertiesEquals(ReceptionProduit expected, ReceptionProduit actual) {
        assertReceptionProduitUpdatableFieldsEquals(expected, actual);
        assertReceptionProduitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceptionProduitAutoGeneratedPropertiesEquals(ReceptionProduit expected, ReceptionProduit actual) {
        assertThat(actual)
            .as("Verify ReceptionProduit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceptionProduitUpdatableFieldsEquals(ReceptionProduit expected, ReceptionProduit actual) {
        assertThat(actual)
            .as("Verify ReceptionProduit relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getDateReception()).as("check dateReception").isEqualTo(expected.getDateReception()))
            .satisfies(a -> assertThat(a.getFournisseur()).as("check fournisseur").isEqualTo(expected.getFournisseur()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReceptionProduitUpdatableRelationshipsEquals(ReceptionProduit expected, ReceptionProduit actual) {
        assertThat(actual)
            .as("Verify ReceptionProduit relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()));
    }
}
