package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class RegleRedevanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegleRedevanceAllPropertiesEquals(RegleRedevance expected, RegleRedevance actual) {
        assertRegleRedevanceAutoGeneratedPropertiesEquals(expected, actual);
        assertRegleRedevanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegleRedevanceAllUpdatablePropertiesEquals(RegleRedevance expected, RegleRedevance actual) {
        assertRegleRedevanceUpdatableFieldsEquals(expected, actual);
        assertRegleRedevanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegleRedevanceAutoGeneratedPropertiesEquals(RegleRedevance expected, RegleRedevance actual) {
        assertThat(actual)
            .as("Verify RegleRedevance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegleRedevanceUpdatableFieldsEquals(RegleRedevance expected, RegleRedevance actual) {
        assertThat(actual)
            .as("Verify RegleRedevance relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getTypeRegle()).as("check typeRegle").isEqualTo(expected.getTypeRegle()))
            .satisfies(a -> assertThat(a.getTaux()).as("check taux").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaux()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getPriorite()).as("check priorite").isEqualTo(expected.getPriorite()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegleRedevanceUpdatableRelationshipsEquals(RegleRedevance expected, RegleRedevance actual) {
        assertThat(actual)
            .as("Verify RegleRedevance relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()))
            .satisfies(a -> assertThat(a.getLocataire()).as("check locataire").isEqualTo(expected.getLocataire()))
            .satisfies(a -> assertThat(a.getGroupeArticle()).as("check groupeArticle").isEqualTo(expected.getGroupeArticle()))
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()));
    }
}
