package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class RegularisationRedevanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegularisationRedevanceAllPropertiesEquals(RegularisationRedevance expected, RegularisationRedevance actual) {
        assertRegularisationRedevanceAutoGeneratedPropertiesEquals(expected, actual);
        assertRegularisationRedevanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegularisationRedevanceAllUpdatablePropertiesEquals(
        RegularisationRedevance expected,
        RegularisationRedevance actual
    ) {
        assertRegularisationRedevanceUpdatableFieldsEquals(expected, actual);
        assertRegularisationRedevanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegularisationRedevanceAutoGeneratedPropertiesEquals(
        RegularisationRedevance expected,
        RegularisationRedevance actual
    ) {
        assertThat(actual)
            .as("Verify RegularisationRedevance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegularisationRedevanceUpdatableFieldsEquals(
        RegularisationRedevance expected,
        RegularisationRedevance actual
    ) {
        assertThat(actual)
            .as("Verify RegularisationRedevance relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a ->
                assertThat(a.getMontant()).as("check montant").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMontant())
            )
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()))
            .satisfies(a ->
                assertThat(a.getDateRegularisation()).as("check dateRegularisation").isEqualTo(expected.getDateRegularisation())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegularisationRedevanceUpdatableRelationshipsEquals(
        RegularisationRedevance expected,
        RegularisationRedevance actual
    ) {
        assertThat(actual)
            .as("Verify RegularisationRedevance relationships")
            .satisfies(a -> assertThat(a.getCalcul()).as("check calcul").isEqualTo(expected.getCalcul()));
    }
}
