package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ScanInconnuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanInconnuAllPropertiesEquals(ScanInconnu expected, ScanInconnu actual) {
        assertScanInconnuAutoGeneratedPropertiesEquals(expected, actual);
        assertScanInconnuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanInconnuAllUpdatablePropertiesEquals(ScanInconnu expected, ScanInconnu actual) {
        assertScanInconnuUpdatableFieldsEquals(expected, actual);
        assertScanInconnuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanInconnuAutoGeneratedPropertiesEquals(ScanInconnu expected, ScanInconnu actual) {
        assertThat(actual)
            .as("Verify ScanInconnu auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanInconnuUpdatableFieldsEquals(ScanInconnu expected, ScanInconnu actual) {
        assertThat(actual)
            .as("Verify ScanInconnu relevant properties")
            .satisfies(a -> assertThat(a.getCodeScanne()).as("check codeScanne").isEqualTo(expected.getCodeScanne()))
            .satisfies(a -> assertThat(a.getEcranOrigine()).as("check ecranOrigine").isEqualTo(expected.getEcranOrigine()))
            .satisfies(a -> assertThat(a.getDateScan()).as("check dateScan").isEqualTo(expected.getDateScan()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getResolu()).as("check resolu").isEqualTo(expected.getResolu()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanInconnuUpdatableRelationshipsEquals(ScanInconnu expected, ScanInconnu actual) {
        assertThat(actual)
            .as("Verify ScanInconnu relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()))
            .satisfies(a -> assertThat(a.getProduitAffecte()).as("check produitAffecte").isEqualTo(expected.getProduitAffecte()));
    }
}
