package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SousFamilleArticleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousFamilleArticleAllPropertiesEquals(SousFamilleArticle expected, SousFamilleArticle actual) {
        assertSousFamilleArticleAutoGeneratedPropertiesEquals(expected, actual);
        assertSousFamilleArticleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousFamilleArticleAllUpdatablePropertiesEquals(SousFamilleArticle expected, SousFamilleArticle actual) {
        assertSousFamilleArticleUpdatableFieldsEquals(expected, actual);
        assertSousFamilleArticleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousFamilleArticleAutoGeneratedPropertiesEquals(SousFamilleArticle expected, SousFamilleArticle actual) {
        assertThat(actual)
            .as("Verify SousFamilleArticle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousFamilleArticleUpdatableFieldsEquals(SousFamilleArticle expected, SousFamilleArticle actual) {
        assertThat(actual)
            .as("Verify SousFamilleArticle relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSousFamilleArticleUpdatableRelationshipsEquals(SousFamilleArticle expected, SousFamilleArticle actual) {
        assertThat(actual)
            .as("Verify SousFamilleArticle relationships")
            .satisfies(a -> assertThat(a.getFamilleArticle()).as("check familleArticle").isEqualTo(expected.getFamilleArticle()));
    }
}
