package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class StockProduitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockProduitAllPropertiesEquals(StockProduit expected, StockProduit actual) {
        assertStockProduitAutoGeneratedPropertiesEquals(expected, actual);
        assertStockProduitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockProduitAllUpdatablePropertiesEquals(StockProduit expected, StockProduit actual) {
        assertStockProduitUpdatableFieldsEquals(expected, actual);
        assertStockProduitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockProduitAutoGeneratedPropertiesEquals(StockProduit expected, StockProduit actual) {
        assertThat(actual)
            .as("Verify StockProduit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockProduitUpdatableFieldsEquals(StockProduit expected, StockProduit actual) {
        assertThat(actual)
            .as("Verify StockProduit relevant properties")
            .satisfies(a ->
                assertThat(a.getQuantiteTheorique())
                    .as("check quantiteTheorique")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getQuantiteTheorique())
            )
            .satisfies(a ->
                assertThat(a.getStockAlerte())
                    .as("check stockAlerte")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getStockAlerte())
            )
            .satisfies(a ->
                assertThat(a.getDateDernierMouvement()).as("check dateDernierMouvement").isEqualTo(expected.getDateDernierMouvement())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockProduitUpdatableRelationshipsEquals(StockProduit expected, StockProduit actual) {
        assertThat(actual)
            .as("Verify StockProduit relationships")
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()))
            .satisfies(a -> assertThat(a.getDepot()).as("check depot").isEqualTo(expected.getDepot()));
    }
}
