package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TarifProduitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifProduitAllPropertiesEquals(TarifProduit expected, TarifProduit actual) {
        assertTarifProduitAutoGeneratedPropertiesEquals(expected, actual);
        assertTarifProduitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifProduitAllUpdatablePropertiesEquals(TarifProduit expected, TarifProduit actual) {
        assertTarifProduitUpdatableFieldsEquals(expected, actual);
        assertTarifProduitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifProduitAutoGeneratedPropertiesEquals(TarifProduit expected, TarifProduit actual) {
        assertThat(actual)
            .as("Verify TarifProduit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifProduitUpdatableFieldsEquals(TarifProduit expected, TarifProduit actual) {
        assertThat(actual)
            .as("Verify TarifProduit relevant properties")
            .satisfies(a ->
                assertThat(a.getMontant()).as("check montant").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMontant())
            )
            .satisfies(a -> assertThat(a.getTypePrix()).as("check typePrix").isEqualTo(expected.getTypePrix()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarifProduitUpdatableRelationshipsEquals(TarifProduit expected, TarifProduit actual) {
        assertThat(actual)
            .as("Verify TarifProduit relationships")
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()));
    }
}
