package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TicketCaisseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCaisseAllPropertiesEquals(TicketCaisse expected, TicketCaisse actual) {
        assertTicketCaisseAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketCaisseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCaisseAllUpdatablePropertiesEquals(TicketCaisse expected, TicketCaisse actual) {
        assertTicketCaisseUpdatableFieldsEquals(expected, actual);
        assertTicketCaisseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCaisseAutoGeneratedPropertiesEquals(TicketCaisse expected, TicketCaisse actual) {
        assertThat(actual)
            .as("Verify TicketCaisse auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCaisseUpdatableFieldsEquals(TicketCaisse expected, TicketCaisse actual) {
        assertThat(actual)
            .as("Verify TicketCaisse relevant properties")
            .satisfies(a -> assertThat(a.getNumero()).as("check numero").isEqualTo(expected.getNumero()))
            .satisfies(a -> assertThat(a.getDateEmission()).as("check dateEmission").isEqualTo(expected.getDateEmission()))
            .satisfies(a -> assertThat(a.getNombreImpressions()).as("check nombreImpressions").isEqualTo(expected.getNombreImpressions()))
            .satisfies(a -> assertThat(a.getContenu()).as("check contenu").isEqualTo(expected.getContenu()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCaisseUpdatableRelationshipsEquals(TicketCaisse expected, TicketCaisse actual) {
        assertThat(actual)
            .as("Verify TicketCaisse relationships")
            .satisfies(a -> assertThat(a.getVente()).as("check vente").isEqualTo(expected.getVente()));
    }
}
