package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransfertStockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertStockAllPropertiesEquals(TransfertStock expected, TransfertStock actual) {
        assertTransfertStockAutoGeneratedPropertiesEquals(expected, actual);
        assertTransfertStockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertStockAllUpdatablePropertiesEquals(TransfertStock expected, TransfertStock actual) {
        assertTransfertStockUpdatableFieldsEquals(expected, actual);
        assertTransfertStockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertStockAutoGeneratedPropertiesEquals(TransfertStock expected, TransfertStock actual) {
        assertThat(actual)
            .as("Verify TransfertStock auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertStockUpdatableFieldsEquals(TransfertStock expected, TransfertStock actual) {
        assertThat(actual)
            .as("Verify TransfertStock relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getDateTransfert()).as("check dateTransfert").isEqualTo(expected.getDateTransfert()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertStockUpdatableRelationshipsEquals(TransfertStock expected, TransfertStock actual) {
        assertThat(actual)
            .as("Verify TransfertStock relationships")
            .satisfies(a -> assertThat(a.getBoutiqueOrigine()).as("check boutiqueOrigine").isEqualTo(expected.getBoutiqueOrigine()))
            .satisfies(a ->
                assertThat(a.getBoutiqueDestination()).as("check boutiqueDestination").isEqualTo(expected.getBoutiqueDestination())
            );
    }
}
