package com.adm.supervision.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UniteMesureAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteMesureAllPropertiesEquals(UniteMesure expected, UniteMesure actual) {
        assertUniteMesureAutoGeneratedPropertiesEquals(expected, actual);
        assertUniteMesureAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteMesureAllUpdatablePropertiesEquals(UniteMesure expected, UniteMesure actual) {
        assertUniteMesureUpdatableFieldsEquals(expected, actual);
        assertUniteMesureUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteMesureAutoGeneratedPropertiesEquals(UniteMesure expected, UniteMesure actual) {
        assertThat(actual)
            .as("Verify UniteMesure auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteMesureUpdatableFieldsEquals(UniteMesure expected, UniteMesure actual) {
        assertThat(actual)
            .as("Verify UniteMesure relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getSymbole()).as("check symbole").isEqualTo(expected.getSymbole()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteMesureUpdatableRelationshipsEquals(UniteMesure expected, UniteMesure actual) {
        // empty method
    }
}
