package com.adm.supervision.domain;

import static com.adm.supervision.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class VenteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVenteAllPropertiesEquals(Vente expected, Vente actual) {
        assertVenteAutoGeneratedPropertiesEquals(expected, actual);
        assertVenteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVenteAllUpdatablePropertiesEquals(Vente expected, Vente actual) {
        assertVenteUpdatableFieldsEquals(expected, actual);
        assertVenteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVenteAutoGeneratedPropertiesEquals(Vente expected, Vente actual) {
        assertThat(actual)
            .as("Verify Vente auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVenteUpdatableFieldsEquals(Vente expected, Vente actual) {
        assertThat(actual)
            .as("Verify Vente relevant properties")
            .satisfies(a -> assertThat(a.getNumeroTicket()).as("check numeroTicket").isEqualTo(expected.getNumeroTicket()))
            .satisfies(a -> assertThat(a.getDateHeure()).as("check dateHeure").isEqualTo(expected.getDateHeure()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getReferencePassager()).as("check referencePassager").isEqualTo(expected.getReferencePassager()))
            .satisfies(a ->
                assertThat(a.getReferenceCarteEmbarquement())
                    .as("check referenceCarteEmbarquement")
                    .isEqualTo(expected.getReferenceCarteEmbarquement())
            )
            .satisfies(a ->
                assertThat(a.getMontantBrut())
                    .as("check montantBrut")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantBrut())
            )
            .satisfies(a ->
                assertThat(a.getMontantRemise())
                    .as("check montantRemise")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantRemise())
            )
            .satisfies(a ->
                assertThat(a.getMontantNet())
                    .as("check montantNet")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantNet())
            )
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVenteUpdatableRelationshipsEquals(Vente expected, Vente actual) {
        assertThat(actual)
            .as("Verify Vente relationships")
            .satisfies(a -> assertThat(a.getBoutique()).as("check boutique").isEqualTo(expected.getBoutique()))
            .satisfies(a -> assertThat(a.getLocataire()).as("check locataire").isEqualTo(expected.getLocataire()));
    }
}
